image: "debian:stretch"

generate-ttf:
  stage: build
  before_script:
    - apt-get update -y
    - apt-get install -y make fonttools python-fontforge
  script:
    - make compile
  artifacts:
    paths:
    - fonts/

test:
  stage: test
  before_script:
    - apt-get update -y
    - apt-get install -y make libharfbuzz-bin
  script:
    - cp -r fonts/* .
    - make test
